### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by SebastienDOMME** [Kvikku/IntuneAssignments#9]
Hello,

I have tried to follow your Wiki but get this error about URL redirection : 
![image](https://github.com/Kvikku/IntuneAssignments/assets/103254620/df72c426-f000-42ea-aceb-a121ad143816)

Here is my setup:
![image](https://github.com/Kvikku/IntuneAssignments/assets/103254620/de4ec0b2-8da0-419e-a7c2-6bbcde306c25)

Regards,
SD.

**Comment by SebastienDOMME** [comment]
Seeam to solve the problem by adding http://localhost to the azure configuration.

**Comment by Kvikku** [comment]
I appreciate you raising the issue and reporting back with a fix that you figured out. I will update the documentation with this fix - thank you very much 😄
